name: Vitest

on:
  push:
    branches:
      - "**"
  pull_request:

jobs:
  vitest:
    runs-on: ubuntu-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
        with:
          version: 11.3.0
      - uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Generate types
        run: pnpm run types
      - name: Build
        run: pnpm run build
      - name: Run Vitest
        run: pnpm run test:workers
